server:
  port: 8083

spring:
  application:
    name: enrollment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/olp_enrollment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-discovery:8761/eureka