spring.application.name=service-discovery

# Standard port for Eureka Server
server.port=8761

# Tell Eureka NOT to register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# (Optional but recommended) Suppress a common warning about missing replica nodes
eureka.server.wait-time-in-ms-when-sync-empty=0